// Arreglo con todas las películas para las cards
const peliculasCards = [
    {
        id: 'outrage',
        nombre: 'Outrage',
        anio: '2010',
        fecha_vista: new Date(2021, 6, 16),
        img_card: 'img/cards/card_outrage.jpg',
        img_card_alt: 'Dos miembros de a Yakuza mirando a cámara y apuntando con un arma',
        link_pagina: '#',
        pick: 'Geor',
    },
    {
        id: 'brick',
        nombre: 'Brick',
        anio: '2005',
        fecha_vista: new Date(2021, 6, 09),
        img_card: 'img/cards/card_brick.jpg',
        img_card_alt: 'Adolescente hablando en una cabina telefónica de noche',
        link_pagina: '#',
        pick: 'Pollo',
    },
    {
        id: 'holy_motors',
        nombre: 'Holy Motors',
        anio: 2012,
        fecha_vista: new Date(2021, 6, 02),
        img_card: 'img/cards/card_holy_motors.jpg',
        img_card_alt: 'Hombre ciego de un ojo parado frente a un grupo de gente',
        link_pagina: 'peliculas/holy_motors.html',
        pick: 'la democracia',
    },
    {
        id: 'black_rainbow',
        nombre: 'Beyond the Black Rainbow',
        anio: 2010,
        fecha_vista: new Date(2021, 5, 25),
        img_card: 'img/cards/card_black_rainbow.jpg',
        img_card_alt: 'Hombre caminando en un pasillo con una luz roja de fondo',
        link_pagina: 'peliculas/black_rainbow.html',
        pick: 'Loco',
    },
    {
        id: 'rumba',
        nombre: 'Rumba',
        anio: 2008,
        fecha_vista: new Date(2021, 5, 18),
        img_card: 'img/cards/card_rumba.jpg',
        img_card_alt: 'Mujer y hombre bailando en un patio de escuela',
        link_pagina: 'peliculas/rumba.html',
        pick: 'Tutte',
    },
    {
        id: 'ravenous',
        nombre: 'Ravenous',
        anio: 1999,
        fecha_vista: new Date(2021, 5, 11),
        img_card: 'img/cards/card_ravenous.jpg',
        img_card_alt: 'Hombre con ropa manchada de sangre sonriendo en un bosque',
        link_pagina: 'peliculas/ravenous.html',
        pick: 'Paz',
    },
    {
        id: 'only_lovers',
        nombre: 'Only Lovers Left Alive',
        anio: 2013,
        fecha_vista: new Date(2021, 5, 04),
        img_card: 'img/cards/card_only_lovers.jpg',
        img_card_alt: 'Mujer y hombre mirando a cámara con un mosaico de patrones circulares de fondo',
        link_pagina: 'peliculas/only_lovers.html',
        pick: 'Geor',
    },
    {
        id: 'juan_muertos',
        nombre: 'Juan de los muertos',
        anio: 2011,
        fecha_vista: new Date(2021, 4, 28),
        img_card: 'img/cards/card_juan.jpg',
        img_card_alt: 'Hombre agarrado de la cornisa de un balcón y una mujer ayudándolo',
        link_pagina: 'peliculas/juan_muertos.html',
        pick: 'Pollo',
    },
    {
        id: 'time_gypsies',
        nombre: 'Time of the Gypsies',
        anio: 1988,
        fecha_vista: new Date(2021, 4, 21),
        img_card: 'img/cards/card_time_gypsies.jpg',
        img_card_alt: 'Grupo de personas mirando un ritual funerio en un río',
        link_pagina: 'peliculas/time_gypsies.html',
        pick: 'Loco',
    },
    {
        id: 'troll_hunter',
        nombre: 'Troll Hunter',
        anio: 2010,
        fecha_vista: new Date(2021, 4, 15),
        img_card: 'img/cards/card_trollhunter.jpg',
        img_card_alt: 'Hombre en una camioneta iluminando a un troll que sale del bosque',
        link_pagina: 'peliculas/trollhunter.html',
        pick: 'Paz',
    },
    {
        id: 'black_sheep',
        nombre: 'Black Sheep',
        anio: 2006,
        fecha_vista: new Date(2021, 4, 14),
        img_card: 'img/cards/card_black_sheep.jpg',
        img_card_alt: 'Taxi rodeado de ovejas, varado en una ruta',
        link_pagina: 'peliculas/black_sheep.html',
        pick: 'Paz',
    },
    {
        id: 'suspiria_2018',
        nombre: 'Suspiria',
        anio: 2018,
        fecha_vista: new Date(2021, 4, 8),
        img_card: 'img/cards/card_suspiria_2018.jpg',
        img_card_alt: 'Una mujer mirando a otra desde el umbral de una puerta',
        link_pagina: 'peliculas/suspiria_2018.html',
        pick: 'Paz',
    },
    {
        id: 'fantastic_fox',
        nombre: 'Fantastic Mr. Fox',
        anio: 2009,
        fecha_vista: new Date(2021, 3, 30),
        img_card: 'img/cards/card_fantastic_fox.jpg',
        img_card_alt: 'Dos zorritos ladrones asomándose de la tapa de una alcantarilla',
        link_pagina: 'peliculas/fantastic_fox.html',
        pick: 'Geor', 
    },
    {
        id: 'muertos_risa',
        nombre: 'Muertos de risa',
        anio: 1999,
        fecha_vista: new Date(2021, 3, 23) ,
        img_card: 'img/cards/card_muertos_risa.jpg',
        img_card_alt: 'Hombre a punto de darle una cachetada a otro hombre',
        link_pagina: '#',
        pick: 'Pollo', 
    },
    {
        id: 'suspiria_1977',
        nombre: 'Suspiria',
        anio: 1977,
        fecha_vista: new Date(2021, 3, 16),
        img_card: 'img/cards/card_suspiria_1977.jpg',
        img_card_alt: 'Mujer pasando por un pasillo iluminado de rojo y entrando a una habitación',
        link_pagina: 'peliculas/suspiria_1977.html',
        pick: 'Loco',
    },
    {
        id: 'antiviral',
        nombre: 'Antiviral',
        anio: 2012,
        fecha_vista: new Date(2021, 3, 9),
        img_card: 'img/cards/card_antiviral.jpg',
        img_card_alt: 'Hombre mirando con preocupación un tubo de ensayo con sangre',
        link_pagina: 'peliculas/antiviral.html',
        pick: 'Paz', 
    },
    {
        id: 'top_secret',
        nombre: 'Top Secret',
        anio: 1984,
        fecha_vista: new Date (2021, 3, 2),
        img_card: 'img/cards/card_top_secret.jpg',
        img_card_alt: 'Hombre al lado de una ventana con los vidrios rotos',
        link_pagina: '#',
        pick: 'Fede', 
    },
    {
        id: 'snatch',
        nombre: 'Snatch',
        anio: 2000,
        fecha_vista: new Date(2021, 2, 26),
        img_card: 'img/cards/card_snatch.jpg',
        img_card_alt: 'Hombre alentando a boxeador en un ring',
        link_pagina: '#',
        pick: 'Geor',    
    },
    {
        id: 'oldboy',
        nombre: 'Oldboy',
        anio: 2003,
        fecha_vista: new Date(2021, 2, 19),
        img_card: 'img/cards/card_oldboy.jpg',
        img_card_alt: 'Hombre con pelo largo sonriendo extrañamente en una habitación',
        link_pagina: 'peliculas/old_boy.html',
        pick: 'Pollo', 
    },
    {
        id: 'enter_void',
        nombre: 'Enter the Void',
        anio: 2009,
        fecha_vista: new Date(2021, 2, 13),
        img_card: 'img/cards/card_enter_void.jpg',
        img_card_alt: 'Hombre y mujer caminando de espaldas en una tienda con muchas luces de colores',
        link_pagina: 'peliculas/enter_void.html',
        pick: 'Loco', 
    },
    {
        id: 'thx_1138',
        nombre: 'THX 1138',
        anio: 1971,
        fecha_vista: new Date(2021, 2, 5),
        img_card: 'img/cards/card_thx1138.jpg',
        img_card_alt: 'Policias enmascarados golpeando a un hombre con palos en una habitación completamente blanca',
        link_pagina: 'peliculas/thx_1138.html',
        pick: 'Loco', 
    },
    {
        id: 'synecdoque',
        nombre: 'Synecdoque, New York',
        anio: 2008,
        fecha_vista: new Date(2021, 1, 27),
        img_card: 'img/cards/card_synecdoque.jpg',
        img_card_alt: 'Hombre y mujer rodeados de mesas mirando hacia arriba',
        link_pagina: 'peliculas/synecdoche.html',
        pick: 'Geor',
    },
    {
        id: 'labyrinth',
        nombre: 'Labyrinth',
        anio: 1986,
        fecha_vista: new Date(2021, 1, 19),
        img_card: 'img/cards/card_labyrinth.jpg',
        img_card_alt: 'Hombre y mujer bailando en un baile de máscaras',
        link_pagina: '#',
        pick: 'Pauleta', 
    },
    {
        id: 'tale_tales',
        nombre: 'Tale of Tales',
        anio: 2015,
        fecha_vista: new Date(2021, 1, 12),
        img_card: 'img/cards/card_tale_tales.jpg',
        img_card_alt: 'Hombre mirando con una lupa una caja de madera',
        link_pagina: '#',
        pick: 'Paz', 
    },
    {
        id: 'mulholland_drive',
        nombre: 'Mulholland Drive',
        anio: 2001,
        fecha_vista: new Date(2021, 1, 5),
        img_card: 'img/cards/card_mulholland_drive.jpg',
        img_card_alt: 'Dos mujeres escuchando por teléfono con atención',
        link_pagina: '#',
        pick: 'Pollo', 
    },
    {
        id: 'perfect_blue',
        nombre: 'Perfect Blue',
        anio: 1997,
        fecha_vista: new Date(2021, 0, 22),
        img_card: 'img/cards/card_perfect_blue.jpg',
        img_card_alt: 'Reflejo de una mujer en un espejo roto',
        link_pagina: '#',
        pick: 'Geor', 
    },
    {
        id: 'heavy_metal',
        nombre: 'Heavy Metal',
        anio: 1981,
        fecha_vista: new Date(2021, 0, 8),
        img_card: 'img/cards/card_heavy_metal.jpg',
        img_card_alt: 'Hombre con uniforme militar con un robot ovalado flotante a su lado',
        link_pagina: '#',
        pick: 'Markus', 
    },
];



/* 
    {
        /* 
        id: ,
        nombre: ,
        anio: ,
        fecha_vista: ,
        img_card: ,
        img_card_alt: ,
        link_pagina: ,
        pick: , 
        */
    //},
//*/