name: CI-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # clones repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # generates types before validating TS
      - name: Generate Nuxt Types
        run: npx nuxi prepare

      - name: TypeScript Check
        run: npm run typecheck

      - name: Build Project
        run: npm run build

      - name: Run Unit and Integration Tests
        run: npm run test:run